# Which role am I running on this machine?
role: "alice"  # or "bob"

cluster:
  self_party: "alice"  # this file is for Alice; Bob's file should set "bob"
  ray_address: "192.168.22.102:6379"
  log_to_driver: true
  ray_mode: true
  parties:
    alice:
      address: "192.168.22.102:60001"
      listen_addr: "0.0.0.0:60001"
    bob:
      address: "192.168.22.102:60002"
      listen_addr: "0.0.0.0:60002"

spu:
  nodes:
    - party: "alice"
      address: "192.168.22.102:37267"
    - party: "bob"
      address: "192.168.22.102:50017"
  runtime_config:
    protocol: "SEMI2K"
    field: "FM128"
  link_desc:
    connect_retry_times: 60
    connect_retry_interval_ms: 1000

psi:
  enabled: true
  key: "uid"
  receiver: "bob"          # for Bob's file, you can set "bob"
  protocol: "ECDH_PSI_2PC"
  sort: true
  output_dir: "psi_results"

data:
  alice_csv: "/home/lianghaonan/jupyter_projects/ju/jupyter-demo/examples/alice_data.csv"
  bob_csv: "/home/lianghaonan/jupyter_projects/ju/jupyter-demo/examples/bob_data.csv"
  keys: "uid"
  drop_keys: "uid"

preprocess:
  fill_unknown_cols: ["education", "default", "housing", "loan"]
  binary_cols: ["default", "housing", "loan", "y"]
  ordinal_cols: ["education", "month"]
  onehot_cols: ["job", "marital", "contact", "poutcome"]
  label_col: "y"
  standardize: true

split:
  train_size: 0.8
  random_state: 1234

xgb:
  num_boost_round: 3
  max_depth: 5
  sketch_eps: 0.05
  objective: "logistic"
  reg_lambda: 0.5
  subsample: 0.4
  base_score: 0.11
  predict_to: "bob"

eval:
  bucket_size: 20
  threshold: 0.17
  confusion_to: "bob"